### ISSUE TITLE
Publish on an exchange with auto-delete flag not working

### ISSUE THREAD

**Issue by Xalip** [rabbitmq/rabbitmq-perf-test#190]
If I'm running following command:

`docker run -it --rm pivotalrabbitmq/perf-test -h amqp://10.0.0.117:5672 -x 1 -e "testExchange" -y 0 -t fanout -ad true`

I'm getting following error: 

```
6:23:23.842 [main] ERROR com.rabbitmq.perf.PerfTest - Main thread caught exception
java.io.IOException: null
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:129)
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:125)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:147)
	at com.rabbitmq.client.impl.ChannelN.exchangeDeclare(ChannelN.java:777)
	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.exchangeDeclare(AutorecoveringChannel.java:242)
	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.exchangeDeclare(AutorecoveringChannel.java:232)
	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.exchangeDeclare(AutorecoveringChannel.java:212)
	at com.rabbitmq.perf.MulticastParams.createProducer(MulticastParams.java:348)
	at com.rabbitmq.perf.MulticastSet.createProducers(MulticastSet.java:226)
	at com.rabbitmq.perf.MulticastSet.run(MulticastSet.java:138)
	at com.rabbitmq.perf.PerfTest.main(PerfTest.java:271)
	at com.rabbitmq.perf.PerfTest.main(PerfTest.java:369)
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - inequivalent arg 'auto_delete' for exchange 'testExchange' in vhost '/': received 'false' but current is 'true', class-id=40, method-id=10)
	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:66)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:502)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:293)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:141)
	... 9 common frames omitted
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - inequivalent arg 'auto_delete' for exchange 'testExchange' in vhost '/': received 'false' but current is 'true', class-id=40, method-id=10)
	at com.rabbitmq.client.impl.ChannelN.asyncShutdown(ChannelN.java:516)
	at com.rabbitmq.client.impl.ChannelN.processAsync(ChannelN.java:346)
	at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:182)
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:114)
	at com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:672)
	at com.rabbitmq.client.impl.AMQConnection.access$300(AMQConnection.java:48)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:599)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
Why is it receiving still false despite the -ad flag? Is the flag only working for queues and not for exchanges?

If created another exchange called test with auto-delete false. In this case the same command with -ad false is properly working.

Any help on this is much appreciated.

**Comment by Xalip** [comment]
solved using the predeclared flag

**Comment by lukebakken** [comment]
I can't reproduce this locally:

```
lbakken@MESSIAEN ~/development/rabbitmq/rabbitmq-perf-test (master=)
$ mvn -q exec:java -Dexec.mainClass=com.rabbitmq.perf.PerfTest -Dexec.args="-x 1 -e testExchange -y 0 -t fanout -ad true"
id: test-093038-071, starting producer #0
id: test-093038-071, starting producer #0, channel #0
id: test-093038-071, time: 1.000s, sent: 57678 msg/s
id: test-093038-071, time: 2.000s, sent: 112091 msg/s
id: test-093038-071, time: 3.000s, sent: 124815 msg/s
id: test-093038-071, time: 4.000s, sent: 131016 msg/s
id: test-093038-071, time: 5.000s, sent: 130370 msg/s
id: test-093038-071, time: 6.000s, sent: 129589 msg/s
^Cid: test-093038-071, sending rate avg: 114888 msg/s
id: test-093038-071, receiving rate avg: 0 msg/s
lbakken@MESSIAEN ~/development/rabbitmq/rabbitmq-perf-test (master=)
$ mvn -q exec:java -Dexec.mainClass=com.rabbitmq.perf.PerfTest -Dexec.args="-x 1 -e testExchange -y 0 -t fanout -ad true"
id: test-093048-581, starting producer #0
id: test-093048-581, starting producer #0, channel #0
id: test-093048-581, time: 1.000s, sent: 54100 msg/s
id: test-093048-581, time: 2.000s, sent: 123183 msg/s
id: test-093048-581, time: 3.000s, sent: 124584 msg/s
id: test-093048-581, time: 4.000s, sent: 127665 msg/s
id: test-093048-581, time: 5.000s, sent: 122854 msg/s
^Cid: test-093048-581, sending rate avg: 110564 msg/s
id: test-093048-581, receiving rate avg: 0 msg/s
```

Also, the `--help` output clearly describes the `-ad` argument:

```
 -ad,--auto-delete <arg>                     should the queue be
                                             auto-deleted, default is true
```
