### ISSUE TITLE
Add option to re-connect to RabbitMQ on PerfTest startup

### ISSUE THREAD

**Issue by gerhard** [rabbitmq/rabbitmq-perf-test#191]
If RabbitMQ is not listening on the expected TCP port when PerfTest starts, PerfTest will exit with status code 1 and the following exception:

```log
Main thread caught exception: java.net.ConnectException: Connection refused (Connection refused)
08:31:42.046 [main] ERROR com.rabbitmq.perf.PerfTest - Main thread caught exception
java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at com.rabbitmq.client.impl.SocketFrameHandlerFactory.create(SocketFrameHandlerFactory.java:60)
	at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:62)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:156)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1106)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1063)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1198)
	at com.rabbitmq.perf.MulticastSet.run(MulticastSet.java:115)
	at com.rabbitmq.perf.PerfTest.main(PerfTest.java:271)
	at com.rabbitmq.perf.PerfTest.main(PerfTest.java:369)
```

The ask is to add an option to PerfTest so that it attempts to reconnect.

Given the following `docker-compose.yml` : 

```yml
# https://docs.docker.com/compose/compose-file/
version: "3.7"

services:
  rabbitmq:
    # https://hub.docker.com/_/rabbitmq
    image: rabbitmq:3.8.0-beta.3
  perf-test:
    # https://hub.docker.com/r/pivotalrabbitmq/perf-test/
    image: pivotalrabbitmq/perf-test:2.7.0
    environment:
      URI: "amqp://guest:guest@rabbitmq:5672/%2f"
      RATE: 1
```

Running `docker-compose up` results in the following:

```
Creating desktop_perf-test_1 ... done
Creating desktop_rabbitmq_1  ... done
Attaching to desktop_perf-test_1, desktop_rabbitmq_1
perf-test_1  | Main thread caught exception: java.net.ConnectException: Connection refused (Connection refused)
perf-test_1  | 08:31:42.046 [main] ERROR com.rabbitmq.perf.PerfTest - Main thread caught exception
perf-test_1  | java.net.ConnectException: Connection refused (Connection refused)
perf-test_1  | 	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
perf-test_1  | 	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
perf-test_1  | 	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
perf-test_1  | 	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
perf-test_1  | 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
perf-test_1  | 	at java.base/java.net.Socket.connect(Socket.java:591)
perf-test_1  | 	at com.rabbitmq.client.impl.SocketFrameHandlerFactory.create(SocketFrameHandlerFactory.java:60)
perf-test_1  | 	at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:62)
perf-test_1  | 	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:156)
perf-test_1  | 	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1106)
perf-test_1  | 	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1063)
perf-test_1  | 	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1198)
perf-test_1  | 	at com.rabbitmq.perf.MulticastSet.run(MulticastSet.java:115)
perf-test_1  | 	at com.rabbitmq.perf.PerfTest.main(PerfTest.java:271)
perf-test_1  | 	at com.rabbitmq.perf.PerfTest.main(PerfTest.java:369)
desktop_perf-test_1 exited with code 1
rabbitmq_1   | 2019-04-16 08:31:48.183 [info] <0.8.0> Feature flags: list of feature flags found:
rabbitmq_1   | 2019-04-16 08:31:48.183 [info] <0.8.0> Feature flags:   [ ] implicit_default_bindings
rabbitmq_1   | 2019-04-16 08:31:48.183 [info] <0.8.0> Feature flags:   [ ] quorum_queue
rabbitmq_1   | 2019-04-16 08:31:48.183 [info] <0.8.0> Feature flags: feature flag states written to disk: yes
rabbitmq_1   | 2019-04-16 08:31:48.198 [info] <0.240.0> ra: meta data store initialised. 0 record(s) recovered
rabbitmq_1   | 2019-04-16 08:31:48.199 [info] <0.245.0> WAL: recovering []
rabbitmq_1   | 2019-04-16 08:31:48.200 [info] <0.249.0>
rabbitmq_1   |  Starting RabbitMQ 3.8.0-beta.3 on Erlang 21.3.4
rabbitmq_1   |  Copyright (C) 2007-2019 Pivotal Software, Inc.
rabbitmq_1   |  Licensed under the MPL.  See http://www.rabbitmq.com/
rabbitmq_1   |
rabbitmq_1   |   ##  ##
rabbitmq_1   |   ##  ##      RabbitMQ 3.8.0-beta.3. Copyright (C) 2007-2019 Pivotal Software, Inc.
rabbitmq_1   |   ##########  Licensed under the MPL.  See http://www.rabbitmq.com/
rabbitmq_1   |   ######  ##
rabbitmq_1   |   ##########  Logs: <stdout>
rabbitmq_1   |
rabbitmq_1   |               Starting broker...
rabbitmq_1   | 2019-04-16 08:31:48.200 [info] <0.249.0>
rabbitmq_1   |  node           : rabbit@ac3a65b8d7d7
rabbitmq_1   |  home dir       : /var/lib/rabbitmq
rabbitmq_1   |  config file(s) : /etc/rabbitmq/rabbitmq.conf
rabbitmq_1   |  cookie hash    : PdVQAZVbQWDCm9fxW8l9ug==
rabbitmq_1   |  log(s)         : <stdout>
rabbitmq_1   |  database dir   : /var/lib/rabbitmq/mnesia/rabbit@ac3a65b8d7d7
rabbitmq_1   | 2019-04-16 08:31:48.214 [info] <0.255.0> Memory high watermark set to 12851 MiB (13475676160 bytes) of 32128 MiB (33689190400 bytes) total
rabbitmq_1   | 2019-04-16 08:31:48.219 [info] <0.257.0> Enabling free disk space monitoring
rabbitmq_1   | 2019-04-16 08:31:48.219 [info] <0.257.0> Disk free limit set to 50MB
rabbitmq_1   | 2019-04-16 08:31:48.223 [info] <0.260.0> Limiting to approx 1048476 file handles (943626 sockets)
rabbitmq_1   | 2019-04-16 08:31:48.223 [info] <0.261.0> FHC read buffering:  OFF
rabbitmq_1   | 2019-04-16 08:31:48.223 [info] <0.261.0> FHC write buffering: ON
rabbitmq_1   | 2019-04-16 08:31:48.225 [info] <0.249.0> Node database directory at /var/lib/rabbitmq/mnesia/rabbit@ac3a65b8d7d7 is empty. Assuming we need to join an existing cluster or initialise from scratch...
rabbitmq_1   | 2019-04-16 08:31:48.225 [info] <0.249.0> Configured peer discovery backend: rabbit_peer_discovery_classic_config
rabbitmq_1   | 2019-04-16 08:31:48.225 [info] <0.249.0> Will try to lock with peer discovery backend rabbit_peer_discovery_classic_config
rabbitmq_1   | 2019-04-16 08:31:48.225 [info] <0.249.0> Peer discovery backend does not support locking, falling back to randomized delay
rabbitmq_1   | 2019-04-16 08:31:48.225 [info] <0.249.0> Peer discovery backend rabbit_peer_discovery_classic_config does not support registration, skipping randomized startup delay.
rabbitmq_1   | 2019-04-16 08:31:48.225 [info] <0.249.0> All discovered existing cluster peers:
rabbitmq_1   | 2019-04-16 08:31:48.225 [info] <0.249.0> Discovered no peer nodes to cluster with
rabbitmq_1   | 2019-04-16 08:31:48.228 [info] <0.43.0> Application mnesia exited with reason: stopped
rabbitmq_1   | 2019-04-16 08:31:48.284 [info] <0.249.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
rabbitmq_1   | 2019-04-16 08:31:48.298 [info] <0.249.0> Waiting for Mnesia tables for 30000 ms, 0 retries left
rabbitmq_1   | 2019-04-16 08:31:48.299 [info] <0.249.0> Feature flag `implicit_default_bindings`: supported, attempt to enable...
rabbitmq_1   | 2019-04-16 08:31:48.299 [info] <0.249.0> Feature flag `implicit_default_bindings`: mark as enabled=state_changing
rabbitmq_1   | 2019-04-16 08:31:48.304 [info] <0.249.0> Feature flags: list of feature flags found:
rabbitmq_1   | 2019-04-16 08:31:48.304 [info] <0.249.0> Feature flags:   [~] implicit_default_bindings
rabbitmq_1   | 2019-04-16 08:31:48.304 [info] <0.249.0> Feature flags:   [ ] quorum_queue
rabbitmq_1   | 2019-04-16 08:31:48.304 [info] <0.249.0> Feature flags: feature flag states written to disk: yes
rabbitmq_1   | 2019-04-16 08:31:48.312 [info] <0.249.0> Waiting for Mnesia tables for 30000 ms, 0 retries left
rabbitmq_1   | 2019-04-16 08:31:48.312 [info] <0.249.0> Feature flag `implicit_default_bindings`: mark as enabled=true
rabbitmq_1   | 2019-04-16 08:31:48.319 [info] <0.249.0> Feature flags: list of feature flags found:
rabbitmq_1   | 2019-04-16 08:31:48.319 [info] <0.249.0> Feature flags:   [x] implicit_default_bindings
rabbitmq_1   | 2019-04-16 08:31:48.319 [info] <0.249.0> Feature flags:   [ ] quorum_queue
rabbitmq_1   | 2019-04-16 08:31:48.319 [info] <0.249.0> Feature flags: feature flag states written to disk: yes
rabbitmq_1   | 2019-04-16 08:31:48.327 [info] <0.249.0> Feature flag `quorum_queue`: supported, attempt to enable...
rabbitmq_1   | 2019-04-16 08:31:48.327 [info] <0.249.0> Feature flag `quorum_queue`: mark as enabled=state_changing
rabbitmq_1   | 2019-04-16 08:31:48.333 [info] <0.249.0> Feature flags: list of feature flags found:
rabbitmq_1   | 2019-04-16 08:31:48.333 [info] <0.249.0> Feature flags:   [x] implicit_default_bindings
rabbitmq_1   | 2019-04-16 08:31:48.334 [info] <0.249.0> Feature flags:   [~] quorum_queue
rabbitmq_1   | 2019-04-16 08:31:48.334 [info] <0.249.0> Feature flags: feature flag states written to disk: yes
rabbitmq_1   | 2019-04-16 08:31:48.341 [info] <0.249.0> Waiting for Mnesia tables for 30000 ms, 0 retries left
rabbitmq_1   | 2019-04-16 08:31:48.341 [info] <0.249.0> Feature flag `quorum_queue`:   migrating Mnesia table rabbit_queue...
rabbitmq_1   | 2019-04-16 08:31:48.350 [info] <0.249.0> Feature flag `quorum_queue`:   migrating Mnesia table rabbit_durable_queue...
rabbitmq_1   | 2019-04-16 08:31:48.359 [info] <0.249.0> Feature flag `quorum_queue`:   Mnesia tables migration done
rabbitmq_1   | 2019-04-16 08:31:48.359 [info] <0.249.0> Feature flag `quorum_queue`: mark as enabled=true
rabbitmq_1   | 2019-04-16 08:31:48.367 [info] <0.249.0> Feature flags: list of feature flags found:
rabbitmq_1   | 2019-04-16 08:31:48.368 [info] <0.249.0> Feature flags:   [x] implicit_default_bindings
rabbitmq_1   | 2019-04-16 08:31:48.368 [info] <0.249.0> Feature flags:   [x] quorum_queue
rabbitmq_1   | 2019-04-16 08:31:48.368 [info] <0.249.0> Feature flags: feature flag states written to disk: yes
rabbitmq_1   | 2019-04-16 08:31:48.376 [info] <0.249.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
rabbitmq_1   | 2019-04-16 08:31:48.393 [info] <0.249.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
rabbitmq_1   | 2019-04-16 08:31:48.393 [info] <0.249.0> Peer discovery backend rabbit_peer_discovery_classic_config does not support registration, skipping registration.
rabbitmq_1   | 2019-04-16 08:31:48.394 [info] <0.249.0> Priority queues enabled, real BQ is rabbit_variable_queue
rabbitmq_1   | 2019-04-16 08:31:48.400 [info] <0.478.0> Starting rabbit_node_monitor
rabbitmq_1   | 2019-04-16 08:31:48.413 [info] <0.249.0> message_store upgrades: 1 to apply
rabbitmq_1   | 2019-04-16 08:31:48.413 [info] <0.249.0> message_store upgrades: Applying rabbit_variable_queue:move_messages_to_vhost_store
rabbitmq_1   | 2019-04-16 08:31:48.414 [info] <0.249.0> message_store upgrades: No durable queues found. Skipping message store migration
rabbitmq_1   | 2019-04-16 08:31:48.414 [info] <0.249.0> message_store upgrades: Removing the old message store data
rabbitmq_1   | 2019-04-16 08:31:48.414 [info] <0.249.0> message_store upgrades: All upgrades applied successfully
rabbitmq_1   | 2019-04-16 08:31:48.430 [info] <0.249.0> Adding vhost '/'
rabbitmq_1   | 2019-04-16 08:31:48.441 [info] <0.513.0> Making sure data directory '/var/lib/rabbitmq/mnesia/rabbit@ac3a65b8d7d7/msg_stores/vhosts/628WB79CIFDYO9LJI6DKMI09L' for vhost '/' exists
rabbitmq_1   | 2019-04-16 08:31:48.444 [info] <0.513.0> Starting message stores for vhost '/'
rabbitmq_1   | 2019-04-16 08:31:48.444 [info] <0.517.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_transient": using rabbit_msg_store_ets_index to provide index
rabbitmq_1   | 2019-04-16 08:31:48.445 [info] <0.513.0> Started message store of type transient for vhost '/'
rabbitmq_1   | 2019-04-16 08:31:48.445 [info] <0.520.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_persistent": using rabbit_msg_store_ets_index to provide index
rabbitmq_1   | 2019-04-16 08:31:48.446 [warning] <0.520.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_persistent": rebuilding indices from scratch
rabbitmq_1   | 2019-04-16 08:31:48.447 [info] <0.513.0> Started message store of type persistent for vhost '/'
rabbitmq_1   | 2019-04-16 08:31:48.449 [info] <0.249.0> Creating user 'guest'
rabbitmq_1   | 2019-04-16 08:31:48.450 [info] <0.249.0> Setting user tags for user 'guest' to [administrator]
rabbitmq_1   | 2019-04-16 08:31:48.451 [info] <0.249.0> Setting permissions for 'guest' in '/' to '.*', '.*', '.*'
rabbitmq_1   | 2019-04-16 08:31:48.455 [info] <0.558.0> started TCP listener on [::]:5672
rabbitmq_1   | 2019-04-16 08:31:48.459 [info] <0.249.0> Setting up a table for connection tracking on this node: tracked_connection_on_node_rabbit@ac3a65b8d7d7
rabbitmq_1   | 2019-04-16 08:31:48.462 [info] <0.249.0> Setting up a table for per-vhost connection counting on this node: tracked_connection_per_vhost_on_node_rabbit@ac3a65b8d7d7
rabbitmq_1   | 2019-04-16 08:31:48.634 [info] <0.8.0> Server startup complete; 0 plugins started.
rabbitmq_1   |  completed with 0 plugins.
```

Ideally, PerfTest would not fail in this scenario. The current workaround is to overwrite the `entrypoint` & `command` in the `docker-compose.yml`:

```yml
# https://docs.docker.com/compose/compose-file/
version: "3.7"

services:
  rabbitmq:
    # https://hub.docker.com/_/rabbitmq
    image: rabbitmq:3.8.0-beta.3
  perf-test:
    # https://hub.docker.com/r/pivotalrabbitmq/perf-test/
    image: pivotalrabbitmq/perf-test:2.7.0
    environment:
      URI: "amqp://guest:guest@rabbitmq:5672/%2f"
      RATE: 1
      entrypoint: []
      command: /bin/bash -c "sleep 10 && bin/runjava com.rabbitmq.perf.PerfTest"
```

**Comment by michaelklishin** [comment]
What's the point of reconnecting if the port is incorrect?

**Comment by gerhard** [comment]
That is a genuine "will never work" scenario.

In the above case, PerfTest starts before RabbitMQ creates an AMQP listener. Rather than PerfTest crashing, there should be a PerfTest option to retry connecting. This option should be disabled by default.

As an improvement to the above `sleep`, we could leverage `nc` to check if the socket is open before starting PerfTest. This feels inferior to having PerfTest handle it natively.

What solution do you have in mind @michaelklishin ?
