### ISSUE TITLE
PerfTestMulti throws NullPointerException

### ISSUE THREAD

**Issue by kenzoawa** [rabbitmq/rabbitmq-perf-test#206]
Recently i was testing with perftest the CLI way but wanted to run reports just so i can have them in written. All works fine but when i enter : 

bin/runjava com.rabbitmq.perf.PerfTestMulti spec-file.js result-file.js

contents of the spec file is : 

```json
[{'name': 'consume', 'type': 'simple', 'uri': 'amqp://rabbitmq_uri',
  'params': [{'time-limit': 30, 'producer-count': 4, 'consumer-count': 2}]}]
```

i get : 

````
Running scenario 'consume' Exception in thread "main" java.lang.NullPointerException
	at java.util.concurrent.CopyOnWriteArrayList.<init>(CopyOnWriteArrayList.java:134)
	at com.rabbitmq.perf.MulticastSet.<init>(MulticastSet.java:79)
	at com.rabbitmq.perf.MulticastSet.<init>(MulticastSet.java:66)
	at com.rabbitmq.perf.SimpleScenario.run(SimpleScenario.java:49)
	at com.rabbitmq.perf.PerfTestMulti.runTests(PerfTestMulti.java:109)
	at com.rabbitmq.perf.PerfTestMulti.runStaticBrokerTests(PerfTestMulti.java:103)
	at com.rabbitmq.perf.PerfTestMulti.main(PerfTestMulti.java:56)
```

Perftest is working fine, only pertestMulti has some kind of problem which i cannot find where exactly is leading me.

**Comment by michaelklishin** [comment]
[SimpleScenario passes URIs as null](https://github.com/rabbitmq/rabbitmq-perf-test/blob/master/src/main/java/com/rabbitmq/perf/SimpleScenario.java#L49) which is incompatible with the code introduced in https://github.com/rabbitmq/rabbitmq-perf-test/commit/16f4e0a730f5f985c4cd5d525e0f4211bcd9ea93.

**Comment by kenzoawa** [comment]
Can i use some workaround around this so i can get reports or ?

Thanks.

**Comment by acogoluegnes** [comment]
@kenzoawa This is a regression introduced in 2.8.0, so you can downgrade to 2.7.0.

**Comment by kenzoawa** [comment]
Thank you @acogoluegnes - with 2.7.0 works everything as expected.
