### ISSUE TITLE
Handle interruption of consumer latency simulation properly

### ISSUE THREAD

**Issue by acogoluegnes** [rabbitmq/rabbitmq-perf-test#207]
A scary stack trace shows up in the console if the run stops while a consumer is simulating latency:

```
nack_1                      | 14:24:45.405 [perf-test-consumer-0-worker-0] ERROR c.r.perf.RelaxedExceptionHandler - Consumer com.rabbitmq.perf.Consumer$ConsumerImpl@2be4d612 (amq.ctag-EYeDoeDEQLwXawvYJ3YhWg) method handleDelivery for channel AMQChannel(amqp://guest@172.24.0.13:5672/,1) threw an exception for channel AMQChannel(amqp://guest@172.24.0.13:5672/,1)
nack_1                      | java.lang.RuntimeException: Exception while simulating latency
nack_1                      |   at com.rabbitmq.perf.Consumer$ThreadSleepConsumerLatency.simulateLatency(Consumer.java:396)
nack_1                      |   at com.rabbitmq.perf.Consumer$ConsumerImpl.handleMessage(Consumer.java:232)
nack_1                      |   at com.rabbitmq.perf.Consumer$ConsumerImpl.handleDelivery(Consumer.java:220)
nack_1                      |   at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
nack_1                      |   at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:104)
nack_1                      |   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
nack_1                      |   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
nack_1                      |   at java.base/java.lang.Thread.run(Thread.java:834)
nack_1                      | Caused by: java.lang.InterruptedException: sleep interrupted
nack_1                      |   at java.base/java.lang.Thread.sleep(Native Method)
nack_1                      |   at com.rabbitmq.perf.Consumer$ThreadSleepConsumerLatency.simulateLatency(Consumer.java:393)
nack_1                      |   ... 7 common frames omitted
nack_1                      | id: test-142345-126, time: 60.226s, sent: 0 msg/s, received: 0.33 msg/s, min/median/75th/95th/99th consumer latency: 60036279/60036279/60036279/60036279/60036279 ?s
```

The interruption of the consumer thread while it is simulating latency should be handled properly to avoid the stack trace.

**Comment by gerhard** [comment]
Testing this now

**Comment by gerhard** [comment]
The original error is no longer present, I'm hitting a slightly different error now:

```
nack_1                      | 16:24:08.127 [perf-test-consumer-0-worker-0] ERROR c.r.perf.RelaxedExceptionHandler - Consumer com.rabbitmq.perf.Consumer$ConsumerImpl@694d06af (amq.ctag--75008d9Bk0uAW5lg7SLvQ) method handleDelivery for channel AMQChannel(amqp://guest@172.23.0.12:5672/,1) threw an exception for channel AMQChannel(amqp://guest@172.23.0.12:5672/,1)
nack_1                      | com.rabbitmq.client.AlreadyClosedException: connection is already closed due to clean connection shutdown; protocol method: #method<connection.close>(reply-code=200, reply-text=Closed by PerfTest, class-id=0, method-id=0)
nack_1                      | 	at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:258)
nack_1                      | 	at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:427)
nack_1                      | 	at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:421)
nack_1                      | 	at com.rabbitmq.client.impl.recovery.RecoveryAwareChannelN.basicNack(RecoveryAwareChannelN.java:106)
nack_1                      | 	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicNack(AutorecoveringChannel.java:433)
nack_1                      | 	at com.rabbitmq.perf.Consumer.lambda$static$1(Consumer.java:42)
nack_1                      | 	at com.rabbitmq.perf.Consumer$ConsumerImpl.lambda$ackIfNecessary$0(Consumer.java:261)
nack_1                      | 	at com.rabbitmq.perf.AgentBase.dealWithWriteOperation(AgentBase.java:80)
nack_1                      | 	at com.rabbitmq.perf.Consumer$ConsumerImpl.ackIfNecessary(Consumer.java:259)
nack_1                      | 	at com.rabbitmq.perf.Consumer$ConsumerImpl.handleMessage(Consumer.java:233)
nack_1                      | 	at com.rabbitmq.perf.Consumer$ConsumerImpl.handleDelivery(Consumer.java:220)
nack_1                      | 	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
nack_1                      | 	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:104)
nack_1                      | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
nack_1                      | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
nack_1                      | 	at java.base/java.lang.Thread.run(Thread.java:834)
```

I'm attaching the entire log file for more info.

[rabbitmq-perf-test-207.log](https://github.com/rabbitmq/rabbitmq-perf-test/files/3262535/rabbitmq-perf-test-207.log)

**Comment by acogoluegnes** [comment]
@gerhard Can you give it a try? I made the logging less noisy for those exceptions, because they typically happen during shutdown or connection recovery. The log level can still be changed when debugging something.

**Comment by gerhard** [comment]
Works a treat, no errors in 15 minutes 👍
