### ISSUE TITLE
Varying tests fail because of timeoutexception

### ISSUE THREAD

**Issue by luos** [rabbitmq/rabbitmq-perf-test#220]
Hi,

I can not run Varying tests because I get a timeoutexception. I fixed it for myself so I can run the tests by commenting the line  at https://github.com/rabbitmq/rabbitmq-perf-test/blob/05c12756b408485360f6b838b233699ed3bdb65e/src/main/java/com/rabbitmq/perf/MulticastSet.java#L416

Seems like the cause is that the first run immediately shuts down the executor. I don't have enough knowledge to tell if this would be the right fix, I am assuming not as now the executor is never shut down? The tests seem to be running fine. 

Maybe I am running the test incorrectly?

Thanks
 

```
➜  rabbitmq-perf-test-2.9.0 bin/runjava com.rabbitmq.perf.PerfTestMulti variable.json xxx.js
Running scenario 'message-sizes' #11:08:40.465 [AMQP Connection 0:0:0:0:0:0:0:1:5672] ERROR c.r.c.impl.ForgivingExceptionHandler - An unexpected connection driver error occured
java.util.concurrent.RejectedExecutionException: Task com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable@7f350b3f rejected from java.util.concurrent.ThreadPoolExecutor@7b0a8001[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 10]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
	at java.base/java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:687)
	at com.rabbitmq.client.impl.ConsumerWorkService.addWork(ConsumerWorkService.java:81)
	at com.rabbitmq.client.impl.ConsumerDispatcher.execute(ConsumerDispatcher.java:214)
	at com.rabbitmq.client.impl.ConsumerDispatcher.handleShutdownSignal(ConsumerDispatcher.java:173)
	at com.rabbitmq.client.impl.ChannelN.broadcastShutdownSignal(ChannelN.java:283)
	at com.rabbitmq.client.impl.ChannelN.finishProcessShutdownSignal(ChannelN.java:301)
	at com.rabbitmq.client.impl.ChannelN.access$000(ChannelN.java:52)
	at com.rabbitmq.client.impl.ChannelN$2.transformReply(ChannelN.java:605)
	at com.rabbitmq.client.impl.ChannelN$2.transformReply(ChannelN.java:602)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.handleCommand(AMQChannel.java:486)
	at com.rabbitmq.client.impl.RpcContinuationRpcWrapper.complete(RpcContinuationRpcWrapper.java:38)
	at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:200)
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:114)
	at com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:672)
	at com.rabbitmq.client.impl.AMQConnection.access$300(AMQConnection.java:48)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:599)
	at java.base/java.lang.Thread.run(Thread.java:830)
11:08:50.464 [main] ERROR com.rabbitmq.perf.PerfTestMulti - Error during test execution
java.io.IOException: java.util.concurrent.TimeoutException
	at com.rabbitmq.perf.MulticastParams$TopologyHandlerSupport.configureQueues(MulticastParams.java:761)
	at com.rabbitmq.perf.MulticastParams$SequenceTopologyHandler.configureAllQueues(MulticastParams.java:886)
	at com.rabbitmq.perf.MulticastParams.configureAllQueues(MulticastParams.java:518)
	at com.rabbitmq.perf.MulticastSet.run(MulticastSet.java:165)
	at com.rabbitmq.perf.MulticastSet.run(MulticastSet.java:150)
	at com.rabbitmq.perf.VaryingScenario.run(VaryingScenario.java:65)
	at com.rabbitmq.perf.VaryingScenario.run(VaryingScenario.java:54)
	at com.rabbitmq.perf.VaryingScenario.run(VaryingScenario.java:44)
	at com.rabbitmq.perf.PerfTestMulti.runTests(PerfTestMulti.java:121)
	at com.rabbitmq.perf.PerfTestMulti.runStaticBrokerTests(PerfTestMulti.java:115)
	at com.rabbitmq.perf.PerfTestMulti.main(PerfTestMulti.java:62)
Caused by: java.util.concurrent.TimeoutException: null
	at com.rabbitmq.utility.BlockingCell.get(BlockingCell.java:77)
	at com.rabbitmq.utility.BlockingCell.uninterruptibleGet(BlockingCell.java:120)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:502)
	at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:622)
	at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:547)
	at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:540)
	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.close(AutorecoveringChannel.java:73)
	at com.rabbitmq.perf.MulticastParams$TopologyHandlerSupport.configureQueues(MulticastParams.java:760)
	... 10 common frames omitted
```

```
[
    {
        "name": "message-sizes",
        "type": "varying",
        "uri": "amqp://guest:guest@localhost:5672",
        "params": [
            {
                "time-limit": 15,
                "producer-count": 10,
                "consumer-count": 10,
                //"flags": ["persistent"],
                "producer-rate-limit": 10,
                "queue-pattern": "queue-2-%d",
                "queue-sequence-from": 1,
                "queue-sequence-to": 50
            }
        ],
        "variables": [{
            "name": "min-msg-size",
            "values": [5000, 10000, 20000, 50000, 100000, 1000000]
        }]
    }
]
```

**Comment by luos** [comment]
Actually the real problem is that setSharedExecutor is called with an ExecutorService with 0 threads and in the next scenario the ExecutorService is still this one which makes it so the threadpool rejecting the new connection.

**Comment by acogoluegnes** [comment]
@luos Thanks for reporting this. The producer thread pool of the first run is indeed re-used by mistake for the configuration connection of the second run. It is actually closed at the end of the first run, hence the error at the beginning of the second run.

The shared executor for the configuration connection is not set, so a default one will be created (at least for the first run). A reasonable solution is to create a single-threaded pool every time, this way PerfTest controls the threads it uses.

Thanks for the analysis, I'll work on a fix.

**Comment by acogoluegnes** [comment]
@luos [2.9.1](https://github.com/rabbitmq/rabbitmq-perf-test/releases/tag/v2.9.1) is available with the fix (I haven't announced it yet though).

**Comment by luos** [comment]
Thank you for the quick fix!
