### ISSUE TITLE
Producer can not generated over 740

### ISSUE THREAD

**Issue by siranohyuk** [rabbitmq/rabbitmq-perf-test#229]
my version is 2.10.0.RC1

my running options here
`./runjava com.rabbitmq.perf.PerfTest --producers 1000 --publishing-interval 1 --producer-scheduler-threads 10 --size 1500 --use-millis`

and result
`id: test-111855-657, starting producer #740
Main thread caught exception: java.util.concurrent.TimeoutException
11:20:16.319 [main] ERROR com.rabbitmq.perf.PerfTest - Main thread caught exception
java.util.concurrent.TimeoutException: null
	at com.rabbitmq.utility.BlockingCell.get(BlockingCell.java:77)
	at com.rabbitmq.utility.BlockingCell.uninterruptibleGet(BlockingCell.java:120)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:502)
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:325)
	at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:64)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:156)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1110)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1067)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:965)
	at com.rabbitmq.perf.MulticastSet$ConnectionCreator.createConnection(MulticastSet.java:730)
	at com.rabbitmq.perf.MulticastSet.createConnection(MulticastSet.java:267)
	at com.rabbitmq.perf.MulticastSet.createProducers(MulticastSet.java:324)
	at com.rabbitmq.perf.MulticastSet.run(MulticastSet.java:173)
	at com.rabbitmq.perf.PerfTest.main(PerfTest.java:325)
	at com.rabbitmq.perf.PerfTest.main(PerfTest.java:445)`

**Comment by michaelklishin** [comment]
Testing with 100s or 1000s of connections will have to use multiple nodes and JVM tuning because every connection has at least one thread and will use at least one file descriptor. Both have resource limits in the [kernel](https://www.rabbitmq.com/networking.html#open-file-handle-limit) or the JVM.
