### ISSUE TITLE
On Docker can't connect to localhost or remote

### ISSUE THREAD

**Issue by adthonb** [rabbitmq/rabbitmq-perf-test#261]
I using this script on Docker but it can't connect to the localhost network. I can `telnet` to RabbitMQ on localhost. I can run on K8S that connect to Service.

This my console output

**$ telnet localhost 5672**
```
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
123456
AMQP    Connection closed by foreign host.
```
**$ docker run -it --rm pivotalrabbitmq/perf-test:latest --uri amqp://user:pass@localhost**
```
Main thread caught exception: java.net.ConnectException: Connection refused (Connection refused)
22:11:52.689 [main] ERROR com.rabbitmq.perf.PerfTest - Main thread caught exception
java.net.ConnectException: Connection refused (Connection refused)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at com.rabbitmq.client.impl.SocketFrameHandlerFactory.create(SocketFrameHandlerFactory.java:60)
        at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:62)
        at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:156)
        at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1130)
        at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1087)
        at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:985)
        at com.rabbitmq.perf.MulticastSet$ConnectionCreator.createConfigurationConnections(MulticastSet.java:774)
        at com.rabbitmq.perf.MulticastSet.createConfigurationConnections(MulticastSet.java:284)
        at com.rabbitmq.perf.MulticastSet.run(MulticastSet.java:162)
        at com.rabbitmq.perf.PerfTest.main(PerfTest.java:353)
        at com.rabbitmq.perf.PerfTest.main(PerfTest.java:473)
```

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
