### ISSUE TITLE
how to config

### ISSUE THREAD

**Issue by R1310328554** [rabbitmq/rabbitmq-perf-test#86]
Hi, good man!

as i known , PerfTest runs on localhost with user "guest" by default, but how can i change this?

or how to solve the below problem ? 

bin/runjava com.rabbitmq.perf.PerfTest -h  amqp://localhost  -x 1 -y 2 -u "throughput-test-1" -a --id "test 1"  
Main thread caught exception: com.rabbitmq.client.AuthenticationFailureException: ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.
com.rabbitmq.client.AuthenticationFailureException: ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:362)
	at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:64)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:134)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:997)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:956)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1084)
	at com.rabbitmq.perf.MulticastSet.run(MulticastSet.java:87)
	at com.rabbitmq.perf.PerfTest.main(PerfTest.java:221)
	at com.rabbitmq.perf.PerfTest.main(PerfTest.java:256)

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
You can specify any credentials (or hostname) you need in the [URI](http://www.rabbitmq.com/uri-spec.html).
