### ISSUE TITLE
Connection is closed when using exclusive and several consumer channels

### ISSUE THREAD

**Issue by acogoluegnes** [rabbitmq/rabbitmq-perf-test#93]
Reported by @gerhard.

When using with the following arguments:
```
--uris amqp://guest:guest@localhost:5672/%2F --size 1000 --interval 30 \ 
  --consumers 1 --producers 1 --auto-delete true --exclusive \ 
  --exchange chx2 --type x-consistent-hash --confirm-timeout 30 \
  --producer-channel-count 10 --consumer-channel-count 10 \
  --routing-key 10 --queue-args x-expires=500,x-message-ttl=5000 --rate 1
```

I am getting this error:

```
2018-04-05T13:59:27.46+0100 [APP/PROC/WEB/0] ERR Main thread caught exception: com.rabbitmq.client.AlreadyClosedException: connection is already closed due to clean connection shutdown; protocol method: #method<connection.close>(reply-code=200, reply-text=Connection not used, class-id=0, method-id=0)
   2018-04-05T13:59:27.46+0100 [APP/PROC/WEB/0] ERR com.rabbitmq.client.AlreadyClosedException: connection is already closed due to clean connection shutdown; protocol method: #method<connection.close>(reply-code=200, reply-text=Connection not used, class-id=0, method-id=0)
   2018-04-05T13:59:27.46+0100 [APP/PROC/WEB/0] ERR 	at com.rabbitmq.client.impl.AMQConnection.ensureIsOpen(AMQConnection.java:172)
   2018-04-05T13:59:27.46+0100 [APP/PROC/WEB/0] ERR 	at com.rabbitmq.client.impl.AMQConnection.createChannel(AMQConnection.java:550)
   2018-04-05T13:59:27.46+0100 [APP/PROC/WEB/0] ERR 	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.createChannel(AutorecoveringConnection.java:143)
   2018-04-05T13:59:27.46+0100 [APP/PROC/WEB/0] ERR 	at com.rabbitmq.perf.MulticastParams$TopologyHandlerSupport.configureQueues(MulticastParams.java:546)
   2018-04-05T13:59:27.46+0100 [APP/PROC/WEB/0] ERR 	at com.rabbitmq.perf.MulticastParams$FixedQueuesTopologyHandler.configureQueuesForClient(MulticastParams.java:613)
   2018-04-05T13:59:27.46+0100 [APP/PROC/WEB/0] ERR 	at com.rabbitmq.perf.MulticastParams.createConsumer(MulticastParams.java:346)
   2018-04-05T13:59:27.46+0100 [APP/PROC/WEB/0] ERR 	at com.rabbitmq.perf.MulticastSet.run(MulticastSet.java:114)
   2018-04-05T13:59:27.46+0100 [APP/PROC/WEB/0] ERR 	at com.rabbitmq.perf.PerfTest.main(PerfTest.java:239)
   2018-04-05T13:59:27.46+0100 [APP/PROC/WEB/0] ERR 	at com.rabbitmq.perf.PerfTest.main(PerfTest.java:313)
```

**Comment by acogoluegnes** [comment]
When using exclusive queues, there's a connection cache involved to re-use connections for the same resources and extra connections are closed because un-used. Unfortunately when using several channels for each consumer, only one connection is involved and it is closed just like any extra connections.
